### ISSUE TITLE
Main window

### ISSUE THREAD

**Issue by hadja20** [clap-esp/clap-qt#16]
Développer la version initiale de la fenêtre principale de l'application. Cela implique de concevoir et de mettre en œuvre la présentation de base, de garantir que toutes les fonctionnalités principales sont accessibles et de configurer des espaces réservés pour les composants clés de l'interface utilisateur. L’objectif est de créer une interface fonctionnelle et conviviale qui servira de plaque tournante centrale pour l’interaction des utilisateurs.

**Comment by Hamza-Ikiou** [comment]
Première version de la page Main :
- MenuBar
- StackView qui permet de naviguer entre la page d'import, de paramètres et de derush
